version: '3.4'
services: 
  db:
    container_name: PostgreSQL
    image: postgres:13.1
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  